package com.yangblog.utils.webapp;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum WebappRetCode {

    BAD_REQUEST(-400), ILLEGAL_ARGUS(-400), METHOD_NOT_ALLOWED(-405), ILLEGAL_STATE(-410), SERVER_ERROR(-500), NOT_FOUND(-404), UNAUTHORIZED(-401),
    FORBIDDEN(-403), TIPS_CUSTOM_ERROR(-420), CUSTOM_ERROR(-420), MOBILE_HAS_REGISTER(-421), BLACK_LIST(-422),
    NO_BINDING_MOBILE(-425), TREASURE_NOT_ENOUGH(-426), NO_RECEIVER(-427), ACCOUNT_ABNORMAL(-428),
    SPECIAL_ID_HAS_BOUND(-430), INVALID_SERIAL_CODE(-431), NOT_A_NEW_TBK_USER(-432), SPECIAL_ID_NOT_MATCH(-433),
    TPWD_ERROR(-434), SUGGEST_EXCEEDING_THE_LIMIT(-435),
    SUCCESS(1);

    private int code;

}
